<DetectSuccess>:
    BoxLayout:
        orientation: 'vertical'
        spacing: 20
        padding: 20
        Label:
            text: "Plat sudah berhasil ditambahkan"
            font_size: 24
            bold: True
            halign: 'center'
            valign: 'middle'

        Button:
            text: "Kembali ke Halaman Utama"
            font_size: 20
            on_release: root.go_to_home()
